### PR TITLE
DM-40186-v24: Update dynamic detection task defaults and logging

### PR DESCRIPTION
**Pull request by mwittgen**

### CODE REVIEW

**Review by laurenam — CHANGES_REQUESTED** [review]
This PR needs an update.  What is currently here was a quick-fix put in (by @yalsayyad) before the final PR was completed and merged.  Could you please update the commits and add the missing two before merging.

**Comment by mwittgen** [comment]
The docstring was already fixed on `v24.0.x` https://github.com/lsst/meas_algorithms/blob/f14d0188e342bf134cecb230fc3235b3554a127b/python/lsst/meas/algorithms/dynamicDetection.py#L117
Added an empty cherry-pick plus the missing one

**Review by laurenam — CHANGES_REQUESTED** [review]
Getting close!  The "Reduce the fraction of sky sources for bg tweak" commit still does not look quite like the one on main: https://github.com/lsst/meas_algorithms/pull/349/commits/552e40f6d3e730d8c2f74f0b981dfa1ac0885645 (e.g. look a the doctoring for `minFractionSourcesFactor`)

**Comment by mwittgen** [comment]
Ah, the v24 branch did already exist. I cherry-picked from scratch and force pushed from scratch now to clean this up.

**Review by laurenam — APPROVED** [review]
Looks good...thanks again!

**Pull request merged**
