### PR TITLE
U/lauren/dm 4821

### PR DESCRIPTION
**Pull request by rearmstr**

### CODE REVIEW

**Comment by rearmstr** [comment]
I would really like to have a better name than footprintBackground.  When I wrote the code, I didn't have anything better, but maybe you can come up with something more descriptive?

**Comment by rearmstr** [comment]
I would probably squash the second commit.  It was just a mistake in the config settings so I don't think we need to preserve it.

**Comment by laurenam** [comment]
The only descriptive names I can think of get quite long. What about tempLocalBackground?

**Comment by laurenam** [comment]
I'll squash those two commits.

**Comment by rearmstr** [comment]
I think tempLocalBackground is much better.

**Comment by laurenam** [comment]
Ok, I'll change it.  I'm inclined to make the name change a separate commit as it may help anyone looking to see if this functionality was ported over.  This way, at least searching through git history for the original name could lead them to the answer.  Do let me know if you disagree!

**Comment by rearmstr** [comment]
Sounds good.

**Comment by jdswinbank** [comment]
Rebased version of this has been merged from tickets/DM-4821.

**Pull request closed without merging**
